### ISSUE TITLE
Get-PublicIP does not work since the API it uses is no longer available: ipv4bot.whatismyipaddress.com

### ISSUE THREAD

**Issue by TyrrellStephen** [buscseik/WifiTools#10]
Calling 'Get-PublicIP' results in an exception (see error record below).

Module used 1.8.3
Platform used: Windows PowerShell 5.1 running on Win10 64-bit 21H2

`Exception             : System.Net.WebException: The remote name could not be resolved: 'ipv4bot.whatismyipaddress.com'
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : System.Net.HttpWebRequest
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-PublicIP, C:\Program Files\WindowsPowerShell\Modules\WifiTools\1.8.3\WifiTools.ps1: line 258
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :`

See WhatIsMyIPAddress's explanation for the removal of their API service(s): https://whatismyipaddress.com/api

**Comment by buscseik** [comment]
Issue is fixed now
