### ISSUE TITLE
Connect-WiFi(): It does not connect to all WiFi Profiles

### ISSUE THREAD

**Issue by schittli** [buscseik/WifiTools#5]
Good evening

Thank you very much for your work and Tools!, 
**it's a real shame that M$ is not supporting you / is not offering this kind of Library.**

#### Connect-WiFi(): It does not connect to all WiFi Profiles
If we use `Get-WifiProfiles()` to list all Profiles, then we get two Profiles listed.
But `Connect-WiFi()` connects only to one profile, on the other, it displays an `Argument Validation Exception`:

```
Connect-WiFi : Cannot validate argument on parameter 'ProfileName'. 
The argument "xxx" does not belong to the set "yyy" specified by the ValidateSet attribute. 
Supply an argument that is in the set and then try the command again.
+ Connect-WiFi -ProfileName xxx
+                           ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Connect-WiFi], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Connect-WiFi
```

It would be very useful if `Connect-WiFi()` could be used to connect to all available WiFi profiles.

Thanks a lot, kind regards,
Thomas

**Comment by buscseik** [comment]
Hi

Could you give me the output of List-WifiProfiles. 
Also, which version of the script is being used?

Krisz

**Comment by buscseik** [comment]
No response since September.
