### ISSUE TITLE
anyway this can support  creating wifi profile of WPA2-enterprise profile with PEAP

### ISSUE THREAD

**Issue by chrisloup** [buscseik/WifiTools#7]
anyway this can support  creating wifi profile of WPA2-enterprise profile with PEAP? it seems there appears to be no way to so without using the native windows GUI?

**Comment by buscseik** [comment]
I can try, but I need an example of the wifi profile. 
Could you export your one and share with me?
Command to export the wifi profile:
netsh wlan export profile name="ProfileName" key=clear folder=c:\Wifi

**Comment by chrisloup** [comment]
ill get it for you once i get into the office probably next week . i heard peap credentials are in an xml

**Comment by thewade** [comment]
The PEAP credentials are not stored in the WLAN profile, and you will not see them if you export the profile.

They are stored in the Windows registry at:
HKLM\SOFTWARE\Microsoft\Wlansvc\UserData\Profiles\{GUID}

You can find tools to encode and decode this on the web. Once set you do not need to enter the credentials for the profile.

There is also WlanSetProfileEapXmlUserData in wlanapi.h but from what I read that does not store the credentials.

Reference:
https://stackoverflow.com/questions/15478107/saving-windows-wireless-profile-credentials
https://learn.microsoft.com/en-us/windows/win32/api/wlanapi/nf-wlanapi-wlansetprofileeapxmluserdata
https://learn.microsoft.com/en-us/windows/win32/eaphost/peap-ms-chapv2-user-properties
